# Form implementation generated from reading ui file 'D:\UEL\HK1\Tuduylaptrinh\5aesieunhan\giaodien2.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(582, 391)
        MainWindow.setStyleSheet("background-color: rgb(255, 231, 243);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(90, 60, 401, 51))
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 0, 331, 61))
        self.label.setStyleSheet("font: 13pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(310, 30, 41, 31))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("D:\\UEL\\HK1\\Tuduylaptrinh\\5aesieunhan\\images/fire.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 330, 121, 21))
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(220, 30, 41, 31))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("D:\\UEL\\HK1\\Tuduylaptrinh\\5aesieunhan\\images/fire.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(50, 120, 501, 181))
        self.groupBox_3.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_7 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(0, 0, 501, 31))
        self.label_7.setStyleSheet("color: rgb(255, 0, 255);\n"
"background-color: rgb(255, 170, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(10, 40, 71, 31))
        self.label_8.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"")
        self.label_8.setObjectName("label_8")
        self.lineEdit_fullname = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.lineEdit_fullname.setGeometry(QtCore.QRect(120, 40, 331, 21))
        self.lineEdit_fullname.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_fullname.setObjectName("lineEdit_fullname")
        self.label_9 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(10, 90, 101, 31))
        self.label_9.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"")
        self.label_9.setObjectName("label_9")
        self.lineEdit_address_total = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.lineEdit_address_total.setGeometry(QtCore.QRect(120, 140, 331, 21))
        self.lineEdit_address_total.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_address_total.setText("")
        self.lineEdit_address_total.setObjectName("lineEdit_address_total")
        self.lineEdit_phonenumber = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.lineEdit_phonenumber.setGeometry(QtCore.QRect(120, 90, 331, 21))
        self.lineEdit_phonenumber.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_phonenumber.setObjectName("lineEdit_phonenumber")
        self.label_10 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(10, 130, 101, 41))
        self.label_10.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(460, 130, 31, 41))
        self.label_11.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"")
        self.label_11.setObjectName("label_11")
        self.pushButton_payment = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_payment.setGeometry(QtCore.QRect(230, 320, 141, 31))
        self.pushButton_payment.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 218, 30);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\UEL\\HK1\\Tuduylaptrinh\\5aesieunhan\\images/pay.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_payment.setIcon(icon)
        self.pushButton_payment.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_payment.setObjectName("pushButton_payment")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 582, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600; color:#ff0000;\">PUREORA TRI ÂN KHÁCH HÀNG-ĐÓN CHÀO NĂM MỚI!!</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#aa007f;\">SIÊU SALE ĐẠI LỄ CUỐI NĂM </span></p><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#aa007f;\">12/12</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#aa007f;\">BRAND: PUREORA </span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Customer\'s Information</p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Full Name:</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Phone number:</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Total:</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p>VNĐ</p></body></html>"))
        self.pushButton_payment.setText(_translate("MainWindow", "THANH TOÁN"))
